pipeline:
  shell_syntax_check:
    image: fpfis/fpfis-base
    commands:
      - for i in $(ls *.sh);do sh -n $i; done
      - for i in $(ls bashrc/*.sh);do sh -n $i; done

  run_init_script:
    image: fpfis/fpfis-base
    commands:
      - ./initCloud9.sh
      - grep -q "devops@ec" ~/.ssh/authorized_keys
      - git config --global user.name
      - git config --global user.email
      - ll ~/.bashrc.d/
      - ll ~/.vimrc.devops
      - composer --version
      - drush --version
      - git st
