pipeline:
  shell_syntax_check:
    image: fpfis/fpfis-base
    commands:
      - for i in $(ls *.sh);do sh -n $i; done

  run_init_script:
    image: centos
    commands:
      - yum install -y sudo
      - yum install -y openssh
      - mkdir ~/.ssh
      - touch ~/.ssh/authorized_keys
      - ./cloud9.sh -h
      - grep -q "devops@ec" ~/.ssh/authorized_keys
      - ./cloud9.sh -m
