pipeline:
  shell_syntax_check:
    image: fpfis/fpfis-base
    commands:
      - for i in $(ls *.sh);do sh -n $i; done
      - ./tests/testMaxLineSize.sh .

  run_init_script:
    image: centos
    privileged: true
    commands:
      - yum install sudo php git -y
      - mkdir ~/.ssh/
      - touch ~/.ssh/authorized_keys
      - ./toolkit.sh -h
      - printf "%s\n" gervasek test "test@example.com" "" "" | ./toolkit.sh -s
      - ./tests/toolkitTests.sh
    when:
      status: [ success, failure ]

