
pipeline:
  test-default:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - cp pillar/default.sls.sample pillar/default.sls
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=default test/aws.json
    when:
      event: [push]

  test-docker:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - cp pillar/default.sls.sample pillar/default.sls
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=docker test/aws.json
    when:
      event: [push]

  test-lamp:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - cp pillar/default.sls.sample pillar/default.sls
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=lamp test/aws.json
    when:
      event: [push]

  create-deploy-production:
      image: fpfis/drone-plugin-github-deploy
      state: create
      deploy_environment: production
      secrets: [ github_api_token ]
      automerge: false
      when:
        event: [push]
        branch: [master]

  push-production:
      image: kroniak/ssh-client
      secrets: [ SALT_MASTER_IP, SALT_MASTER_KEY ]
      commands:
        - echo "$SALT_MASTER_KEY" > /deploy.key
        - chmod 600 /deploy.key
        - ssh -o StrictHostKeyChecking=no -i /deploy.key ec2-user@$SALT_MASTER_IP sudo git -C "/srv/cloud9/" pull
      when:
        event: deployment

