pipeline:
  shell_syntax_check:
    image: fpfis/fpfis-base
    commands:
      - for i in $(ls *.sh);do sh -n $i; done

  run_init_script:
    image: centos
    commands:
      - yum install -y sudo openssh-clients-7.4p1-16.el7.x86_64 which
      - set -x
      - mkdir ~/.ssh
      - touch ~/.ssh/authorized_keys
      - ./cloud9.sh -h
      - grep -q "devops@ec" ~/.ssh/authorized_keys
      - echo -e "\n\n\n\n\n"|./cloud9.sh -m
