pipeline:
  shell_syntax_check:
    image: fpfis/fpfis-base
    commands:
        - for i in $(ls *.sh);do sh -n $i; done
        
  test_init_script:
    image: fpfis/fpfis-base
    commands:
        - ./toolkit.sh
        
  test_default_commands:
    image: fpfis/fpfis-base
    commands:
      - composer --version
      - git st
      - ll *