pipeline:
  shell_syntax_check:
    image: fpfis/fpfis-base
    commands:
      - for i in $(ls *.sh);do sh -n $i; done

  run_init_script:
    image: centos
    commands:
      - yum -y update
      - yum provides php56
      - yum install -y git sudo openssh-clients which
      - mkdir ~/.ssh
      - touch ~/.ssh/authorized_keys
      - ./cloud9.sh -h
      - grep -q "devops@ec" ~/.ssh/authorized_keys
      - echo -e "\n\n\n\n\n"|./cloud9.sh -t
