pipeline:
  shell_syntax_check:
    image: fpfis/fpfis-base
    commands:
      - for i in $(ls *.sh);do sh -n $i; done
      - ./tests/testMaxLineSize.sh .

  run_init_script:
    image: fpfis/fpfis-base
    commands:
      - ./toolkit.sh

  test_devops_key:
    image: fpfis/fpfis-base
    commands:
      - grep -q "devops@ec" ~/.ssh/authorized_keys

  test_git_config:
    image: fpfis/fpfis-base
    commands:
      - git config --global user.name
      - git config --global user.email

  test_default_commands:
    image: fpfis/fpfis-base
    commands:
      - composer --version

  test_default_aliases: 
    image: fpfis/fpfis-base
    commands:
      - git st
      - ll