version: '3'
services:
  web:
    image: fpfis/php56-dev
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      - DOCUMENT_ROOT=${PWD}/build
      - XDEBUG_CONFIG=idekey=cloud9ide remote_connect_back=0 remote_host=172.18.0.1
    depends_on:
      - mysql
    ports:
      - 8080:8080
  mysql:
    image: fpfis/mysql56
  solr:
    image: fpfis/solr5
